### ISSUE TITLE
Harden a dokuwiki installation on a SWAG containerized webhost. 

### ISSUE THREAD

**Issue by RottenRonnie** [eliegkassouf/passwordless-security-guide-for-beginners#1]
I'm just going to leave this here as I'm a bit out of my depth when trying to add Oauth2 etc to an existing website. 
Host is Ubuntu 20.04
server runs docker swag container
hosting dokuwiki 

Do you have any idea of where I can source a guide or similar? 
Thanks

**Comment by eliegkassouf** [comment]
I'm going to be indisposed for a while here so I'll post initial comments.
I imagine you'll want to link your Google Account Ron?

<hr>

### OAUTH2 Basics for any service (mostly all the same):

1. Create a new "Site/App" on the google developer platform or whatever service you're using.
2. Register your domain and green light it in the OAUTH2 setup. I have a feeling that you will simply use localhost? you need to green light your domains with most services.
3. Build OAUTH2 URL for service it starts like: "https://accounts.google.com/o/oauth2/v2/auth" and you need to add the following params to comply with your setup:

**_Example of URL to forward user to:_**
>https://accounts.google.com/o/oauth2/v2/auth?
 scope=https%3A//www.googleapis.com/auth/drive.metadata.readonly&
 access_type=offline&
 include_granted_scopes=true&
 response_type=code&
 state=state_parameter_passthrough_value&
 redirect_uri=https%3A//oauth2.example.com/code&
 client_id=client_id

4. Google will forward you back to your site with the preset redirect_uri. You will need to configure this in the OAUTH2 config on google developer console as well as provide it in the URL. 

5. They will provide you with a token and you need to contact their API one last time to get the email address, name and other data.

<hr>

### Notes:
- Google will not let you access private data easily. If you ever make your app public, you need to send them a video as to why you request this access. This should not be an issue for simply validating Email/Authentication.
- I suggest you use/supply <b>state</b> params and verify it when google forwards back to your service.They will also forward the state.
- Services like AppleID will only send you specific details on the first request so make you capture what you need or else the user needs to de-register on their end and that will be pain.

<hr>

### References:

- Google Link 1 ➡️ [Setting up OAuth 2.0](https://support.google.com/cloud/answer/6158849?hl=en)
- Google Link 2 ➡️ [Using OAuth 2.0 for Web Server Applications](https://developers.google.com/identity/protocols/oauth2/web-server)
